_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 10

loss_fn:
  _target_: torch.nn.CrossEntropyLoss

additional_metrics:
  _target_: torchmetrics.MetricCollection
  metrics:
    - _target_: torchmetrics.Accuracy
      task: "multiclass"
      num_classes: 10
    - _target_: torchmetrics.F1Score
      task: "multiclass"
      average: "macro"
      num_classes: 10

track_best_val_metrics:
  - true # For Accuracy
  - true # For F1 Score

# compile model for faster training with pytorch 2.0
compile: false
